export const chronicDiseases: { name: string }[] = [
  { name: "Diabetes mellitus" },
  { name: "Hypertension" },
  { name: "Cardiovascular diseases" },
  { name: "Chronic obstructive pulmonary disease" },
  { name: "Asthma" },
  { name: "Chronic kidney disease" },
  { name: "Arthritis" },
  { name: "Cancer" },
  { name: "Alzheimer's disease and other dementias" },
  { name: "Chronic liver disease" },
  { name: "HIV/AIDS" },
  { name: "Multiple sclerosis" },
  { name: "Parkinson's disease" },
  { name: "Inflammatory bowel disease" },
  { name: "Fibromyalgia" },
  { name: "Chronic fatigue syndrome" },
  { name: "Osteoporosis" },
  { name: "Thyroid disorders" },
  { name: "Sickle cell anemia" },
  { name: "Lupus" },
  { name: "Cystic fibrosis" },
  { name: "Epilepsy" },
  { name: "Endometriosis" },
  { name: "Migraine headaches" },
  { name: "Chronic pain disorders" }
];
